#!/usr/bin/env bash
# regenerate include/linux/ksu_hidden_syms.h from a built tree

# usage: scripts/gen_ksu_hidden_syms.sh <out-dir> [llvm-nm]
set -euo pipefail

OUT=${1:?usage: $0 <out-dir> [nm]}
NM=${2:-llvm-nm}
MAP="$OUT/System.map"
HDR="include/linux/ksu_hidden_syms.h"

[ -f "$MAP" ] || { echo "no $MAP - build first"; exit 1; }

PREFIXES='^ksu_|^__ksu_|^susfs_|^ksud|^is_ksu_|^is_manager_|^escape_to_|^setup_selinux|^track_throne|^on_post_fs_data|^try_umount|^kernelsu|^__initcall__kmod_kernelsu|^apply_kernelsu|^handle_sepolicy|^getenforce|^setenforce|^is_zygote'

tmp=$(mktemp)
trap 'rm -f "$tmp" "$tmp.cnt"' EXIT

# text symbols in the KSU archive and the out-of-tree susfs object (selinux_hide.o is already in built-in.a)
{ "$NM" --defined-only "$OUT/drivers/kernelsu/built-in.a";
  "$NM" --defined-only "$OUT/fs/susfs.o"; } 2>/dev/null \
  | awk '$2 ~ /^[tT]$/ {print $3}' | LC_ALL=C sort -u > "$tmp"

awk '{print $3}' "$MAP" | LC_ALL=C sort | uniq -c > "$tmp.cnt"

hide=$(mktemp)
while read -r sym; do
	echo "$sym" | grep -qE "$PREFIXES" && continue
	cnt=$(awk -v s="$sym" '$2==s{print $1; f=1} END{if(!f)print 0}' "$tmp.cnt")
	[ "$cnt" = "1" ] && echo "$sym" >> "$hide"
done < "$tmp"
LC_ALL=C sort -u -o "$hide" "$hide"

{
	echo "/* SPDX-License-Identifier: GPL-2.0 */"
	echo ""
	echo "/* auto-generated by scripts/gen_ksu_hidden_syms.sh - do not edit */"
	echo "#ifndef _LINUX_KSU_HIDDEN_SYMS_H"
	echo "#define _LINUX_KSU_HIDDEN_SYMS_H"
	echo ""
	echo "static const char * const ksu_hidden_syms[] = {"
	while read -r s; do echo "	\"$s\","; done < "$hide"
	echo "};"
	echo ""
	echo "#endif /* _LINUX_KSU_HIDDEN_SYMS_H */"
} > "$HDR"

echo "wrote $HDR ($(wc -l < "$hide") names)"
rm -f "$hide"
